config/routes.rb
Railscamp::Application.routes.draw do
  

  get "verifys/edit"

  get "verify/edit"

  get "sessions/new"
  resources :verifys
  resources :password_resets

  resources :floads

  resources :comments
  resources :microposts do
resources :comments
resources :floads
end

  resources :users
  resources :invites
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :projects, :only=> [:index, :create, :destroy, :new, :edit, :show, :update, :discuss, :verify]do
	resources :invites
	resources :microposts
        resources :floads 
        

end
match '/notification', :to  => 'users#notification'
get "edit1_user"  => "users#edit1"
get "new_resetpasses"  => "resetpasses#new"
match '/signin',  :to => 'sessions#new'
match '/signout',  :to => 'sessions#destroy'
match '/signup',  :to => 'users#new'
match '/help',    :to   => 'staticpages#help'
  match '/about',   :to => 'staticpages#about'
  match '/contact', :to => 'staticpages#contact'
  match 'projects/show', :to => 'projects#show'
  match 'microposts/show', :to => 'microposts#show'
  get "microposts/show"
  get "projects/show"
  get "staticpages/home"

 get "staticpages/home"
 get "staticpages/about"
 get "staticpages/contact"

   root :to => 'staticpages#index'

match '*a', :to => 'errors#routing'
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  @projects = current_user.projects.build if signed_in?
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/index.html.erb
<html>
<head>
</head>
<body>

 <div class="clr"></div>

<!--main-container start-->
<div class="main-container"> 
  
  <!--header wrapper start-->
  <div class="header-wrapper"> 
    <!--slider start-->
    <div id="showcase" class="showcase">
      <div class="showcase-slide">
        <div class="showcase-content">
          <div class="showcase-content-wrapper"> 
            <!--content area start-->
            <div class="header">
              <div class="header-col-1"><img src="images/hdr-image.png" alt="" /></div>
              <div class="header-col-2">
                <h2>A central, collaborative work- place to track and complete projects</h2>
                <p>Invite your team to a shared project workspace and efficiently manage roles, permissions, schedules, and responsibilities.</p>
                <div class="left"><%= link_to image_tag("/images/signup-now-btn.png",:alt=>""), signup_path %></div>
              </div>
            </div>
            <!--content area end--> 
          </div>
        </div>
      </div>
      <div class="showcase-slide">
        <div class="showcase-content">
          <div class="showcase-content-wrapper"> 
            <!--content area start-->
            <div class="header">
              <div class="header-col-1"><img src="images/hdr-image.png" alt="" /></div>
              <div class="header-col-2">
                <h2>A central, collaborative work- place to track and complete projects</h2>
                <p>Invite your team to a shared project workspace and efficiently manage roles, permissions, schedules, and responsibilities.</p>
                <div class="left"><%= link_to image_tag("/images/signup-now-btn.png",:alt=>""), signup_path %></div>
              </div>
            </div>
            <!--content area end--> 
          </div>
        </div>
      </div>
      <div class="showcase-slide">
        <div class="showcase-content"> 
          <!--content area start-->
          <div class="header">
            <div class="header-col-1"><img src="images/hdr-image.png" alt="" /></div>
            <div class="header-col-2">
              <h2>A central, collaborative work- place to track and complete projects</h2>
              <p>Invite your team to a shared project workspace and efficiently manage roles, permissions, schedules, and responsibilities.</p>
              <div class="left"><%= link_to image_tag("/images/signup-now-btn.png",:alt=>""), signup_path %></div>
            </div>
          </div>
          <!--content area end--> 
        </div>
      </div>
    </div>
    <!--slider end--> 
  </div>
  <!--header wrapper end-->
  
  <!--bottom-container start-->
  <div class="bottom-container">
  <div class="colm-1">
    <img src="images/manage-projects-online.png" alt="" />
    </div>
  <div class="colm-2">
  <div class="bx-1">
  <div class="left"><img src="images/define-teams.jpg" alt="" /></div>
  <div class="clr"></div>
  <p><strong>Define teams &amp; roles</strong></p>
  </div>
  <div class="bx-1">
  <div class="left"><img src="images/schedules.jpg" alt="" /></div>
  <div class="clr"></div>
  <p><strong>Schedule all your project dates</strong></p>
  </div>
  <div class="bx-1">
  <div class="left"><img src="images/integrated-with-google.jpg" alt="" /></div>
  <div class="clr"></div>
  <p><strong>Integrated with Google across the board</strong></p>
  </div>
  </div>
  </div>
  <!--bottom-container end--> 
  
</div>
<!--main-container end-->  
<% if current_user %> 
<% if current_user.verify==0 %> 
<div id="verify" class="white_content">
 <div class="popup-overlay-bg">
<!--popup-window start-->
   <div class="popup-window">
     <div class="popup-tp-bg"></div>
       <div class="popup-mid-bg">
         <div class="popup-wrapper">
            
 <font color='red'><h2> You Did't verify Your Email Yet Please verify it !</h2> </font>

           <div align="right" id="cancel_btn">
  <%= link_to image_tag("/images/cancel-btn.png"), signout_path, :method=> "delete" %>            
           </div>
         </div>
       </div>
     </div>
   </div>
<!--popup-window end-->
 </div>
</div>
<!--preview End-->
<% end %>
<% end %>
<script type="text/javascript">
$(document).ready(function(){
$(".home-btn").hide();
$("#verify").show();
});
</script>
</body>
</html>
  