config/routes.rb
Railscamp::Application.routes.draw do
  

  get "verifys/edit"

  get "verify/edit"

  get "sessions/new"
  resources :verifys
  resources :password_resets

  resources :floads

  resources :comments
  resources :microposts do
resources :comments
resources :floads
end

  resources :users
  resources :invites
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :projects, :only=> [:index, :create, :destroy, :new, :edit, :show, :update, :discuss, :verify]do
	resources :invites
	resources :microposts
        resources :floads 
        

end
match '/notification', :to  => 'users#notification'
get "edit1_user"  => "users#edit1"
get "new_resetpasses"  => "resetpasses#new"
match '/signin',  :to => 'sessions#new'
match '/signout',  :to => 'sessions#destroy'
match '/signup',  :to => 'users#new'
match '/help',    :to   => 'staticpages#help'
  match '/about',   :to => 'staticpages#about'
  match '/contact', :to => 'staticpages#contact'
  match 'projects/show', :to => 'projects#show'
  match 'microposts/show', :to => 'microposts#show'
  get "microposts/show"
  get "projects/show"
  get "staticpages/home"

 get "staticpages/home"
 get "staticpages/about"
 get "staticpages/contact"

   root :to => 'staticpages#index'

match '*a', :to => 'errors#routing'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  attr_accessible :project_name, :company_name, :data
validates_uniqueness_of :project_name, :scope => :company_name, :message => "Project with same Company name already exist"
has_many :invites, :dependent => :destroy
has_many :floads, :dependent => :destroy
has_many :microposts, :dependent => :destroy
has_many :comments, :dependent => :destroy

validates :company_name,:presence => true,
                    :length   => { :maximum => 23 }
validates :project_name,:presence => true,
                    :length   => { :maximum => 18 }

  def to_param
    project_name
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_filter :signed_in_user, :only=> [:index, :create, :destroy, :new, :edit, :show, :discuss]
before_filter :correct_user,   :only=> :destroy

@invites=Invite.all


	def show
		@user = User.all
		@project = Project.find_by_project_name(params[:id])

                  @owner=User.find_by_id(@project.user_id)
		if @project
		@invites = Invite.all
		@invites = @project.invites(:page => params[:page])
		
		@microposts = Micropost.all
		@microposts = @project.microposts(:page => params[:page])
                
		@floads = Fload.all
		@floads = @project.floads(:page => params[:page])
		@micropost=Micropost.new
		@comment=Comment.new
		else
		(render :file => "#{Rails.root}/public/422.html", :status => 422, :layout => false)
		end		
		
             
	end
#-------------------	
	def new
		 @project=Project.new
                 
  	end
#-------------------	
	def edit
		 @project=Project.find_by_project_name(params[:id])
	end
#-------------------	
	def discuss
		 @project=Project.find_by_project_name(params[:id])
	end
#-------------------	
	def index
		@invites=Invite.all		 
		@projects=Project.all
               @user=User.all
	end
#-------------------	
	def create
                @project = current_user.projects.build(params[:project])
		@owner=current_user.name		    
                @invites=Invite.all
		    if @project.save
			      
			      redirect_to projects_path,:flash =>   {:notice => "Project created"} 
		    else
			     render 'new'
		    end
	end
#-------------------	
def del
@project = Project.find_by_project_name(params[:id])
end	
def destroy
		@project = Project.find_by_project_name(params[:id])
           
		if @project.destroy
                
		redirect_to projects_path,:flash =>   {:notice => "project deleted "}
                else
                render 'edit'
                end 
	end
#-------------------	
	def update
		 @project=Project.find_by_project_name(params[:id])
                 @invites=Invite.all
		  if @project.update_attributes(params[:project])
		      
		      redirect_to project_path(@project),:flash =>   {:error => "Project Updated. "} 
		else
		      render 'static_pages/home'
	       end
       end
#-------------------	
  private

	def correct_user
      		@project = current_user.projects.find_by_project_name(params[:id])
	        redirect_to project_path if @project.nil?
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
def snippet(thought)

wordcount = 3

thought.split[0..(wordcount-1)].join(" ") + (thought.split.size > wordcount ? ".." : "")

end 
def ksnippet(thought)

truncate(thought, :length => 70)

end 

end

app/views/projects/_create_dis.html.erb
<html>
<div style="clear:both">
	
	
		<br><hr><br>
		<div align="center">
				<font face="times, serif" size="6" >
					<b>Discussions<b>
				</font>
				<hr width="40">
		</div>	
			<%= form_for [@project,@micropost] do |f| %>
				<br><br>	
			     <div align="left" class="field" style="width:200%;" >
		       		<b>Content: </b><br>
				<%= f.text_area :content, :rows=> 4, :cols=> 140,:style => 'background-color:#F6CEF5;resize: none; ' %>
 			        <%= f.file_field :photo  %>
			     
					
		  	    <div class="actions" >
		    		<%= f.submit %>
		  	     </div>
				</div>
			<% end %>
    	 
</div>

app/views/projects/_dis_show.html.erb
<html>
<div  align="left">
                <br><hr><br>
	<div align="center">
			<font face="times, serif" size="6" >
				<b>Discussions<b>
			</font>
			<hr width="140">
	</div>
<% @project.microposts.each do |m| %>
	     <div>	
		
		<div style="float:left">
					<% if m.user.has_photo? %>
      						<%= image_tag m.user.photo_path, {:height => 50, :width=> 50} %>
			  		<% else %>
			      			<%= image_tag("/photo_store/no_photo.jpg", :alt => "No image",:height => 45, :width=> 45) %>
					<% end %><br>
					<font size=2 >
					<%= link_to m.user.name, m.user %>&nbsp;&nbsp;
					</font>
		</div>
		<div style="float:left; ;width:600px;margin-top: 5px;margin-bottom: 5px">
			
	   			<div class="content" > 
					<font size=4 color="brown"><b>
						<%= m.content %></b>
						</font>
						
				</div>
		</div>

		<div style="float:right;margin-top: 5px;margin-bottom: 5px">
    			<div class="timestamp"> 
			   <font size=2>

		<% if m.has_photo? %>
      		<% foo = m.extension %>
	<% if foo == "pdf" %>
		  <%= link_to (image_tag("/fileimage/pdf.gif", :alt => "No image",:height => 20, :width=> 20)), m.photo_path %>
                  <%= foo %>
	<% else if foo == "doc" || foo == "docx"  %>
		<%= link_to (image_tag("/fileimage/doc.gif", :alt => "No image",:height => 20, :width=> 20)), m.photo_path %>
                <%= foo %>
	<% else if foo == "odt" %>
		<%= link_to (image_tag("/fileimage/doc.gif", :alt => "No image",:height => 20, :width=> 20)), m.photo_path %>
                <%= foo %>
	<% else if foo == "ppt" || foo == "pptx" %>
		<%= link_to (image_tag("/fileimage/ppt.gif", :alt => "No image",:height => 20, :width=> 20)), m.photo_path %>
 		<%= foo %>
	<% else if (foo == "png" || foo == "jpg") || (foo == "jpeg" || foo == "gif" )%>
		<%= link_to (image_tag(m.photo_path, :alt => "No image",:height => 20, :width=> 20)), m.photo_path %>
		<%= foo %>
	<% else %>
		<%= link_to (image_tag("/fileimage/other.gif", :alt => "No image",:height => 20, :width=> 20)), m.photo_path %>
		<%= foo %>
	<% end %><% end %>
	<% end %>
	<% end %>
	<% end %>
			  		
					<% end %>

                            &nbsp;&nbsp;&nbsp; <%= time_ago_in_words(m.created_at) %>
			   	(<%= link_to m.comments.count ,m %>)
		            </font> 
			</div>
		</div>


		     
	     </div>
<br>
<br><br><br>
<div id="displayFramediv"  align="left" style="margin-left:50px;">
		<br>
		<div >
	   		<% m.comments.each do |comment| %>
			<div style="float:left;width:700px;" >
			 	<div style="float:left;width:100px;">
			    		<% if comment.user.has_photo? %>
			      			<%= image_tag comment.user.photo_path, {:height => 45, :width=> 45} %>
				  	<% else %>
				      		<%= image_tag("/photo_store/no_photo.jpg", :alt => "No image",:height => 45, :width=> 45) %>
			
				      	<% end %><br>
					<font size=2 >
						<%= link_to comment.user.name, comment.user %>
					</font>
				 </div>
				<div style="float:left;width:450px;">
			   		<div style="float:left;margin-top: 5px;margin-bottom: 5px" ALIGN="LEFT">			
						<font size=4 style="align:left">
							<%= comment.content%>
						</font>
			   		</div>
				</div>
				<div style="float:right;margin-top: 10px;margin-bottom: 10px">		
					<div class="timestamp">
					   <font size=2>	
						 <% if comment.has_photo? %>
			
						<% foo = comment.extension %>
						<% if foo == "pdf" %>
							  <%= link_to (image_tag("/fileimage/pdf.gif", :alt => "No image",:height => 20, :width=> 20)), comment.photo_path %>
								<%= foo %>
						<% else if foo == "doc" || foo == "docx"  %>
							<%= link_to (image_tag("/fileimage/doc.gif", :alt => "No image",:height => 20, :width=> 20)), comment.photo_path %>
							<%= foo %>
						<% else if foo == "odt" %>
							<%= link_to (image_tag("/fileimage/doc.gif", :alt => "No image",:height => 20, :width=> 20)), comment.photo_path %>
							<%= foo %>
						<% else if foo == "ppt" || foo == "pptx" %>
							<%= link_to (image_tag("/fileimage/ppt.gif", :alt => "No image",:height => 20, :width=> 20)), comment.photo_path %>
							<%= foo %>
						<% else if (foo == "png" || foo == "jpg") || (foo == "jpeg" || foo == "gif" )%>
							<%= link_to (image_tag(comment.photo_path, :alt => "No image",:height => 20, :width=> 20)), comment.photo_path %>
							<%= foo %>
						<% else %>
							<%= link_to (image_tag("/fileimage/other.gif", :alt => "No image",:height => 20, :width=> 20)), comment.photo_path %>
							<%= foo %>
						<% end %><% end %><% end %><% end %> <% end %>     		
					  		
						<% end %>
		
						&nbsp;&nbsp;&nbsp;<%= time_ago_in_words(comment.created_at) %>
					   </font>
					</div>
				</div>
			</div>		
		<% end %>
		</div>
		
		<div style="clear:both;"> 
			<%= form_for [m, @comment]  do |f| %><br>
				<div class="field">
			    				<%= f.text_area :content ,:size => "50x2" ,:style => 'background-color:#FFFACD;resize: none; '%>
							<%= f.file_field :photo  %>
				</div>
				<div class="actions">
					<%= f.submit %>
				</div>

			<% end %>
			<br>
		</div>

	</div>
		

	<% end %>
</div>

app/views/projects/_emp.html.erb
<html>
<div>
	<br><br>
	<div id="displaydiv" style="display:none";>
		<br><hr><br><font face="times, serif" size="6"><b>Employees<b></font><br><br>
		<% @project.invites.each do |friend| %>
		<div style="margin:10px; float:left; width:160px; height:200px;" align="center">	   	
		  <div align="center" class="hoverMe" style="margin:10px; float:left; width:160px; height:200px; border:2px solid #6E6E6E;">
	         	<br><h5><% count=0 %>
		     	<% @user.each do |u| %><% count=count+1 %>
					<% if friend.mail == u.email %>
                        	             
						<% if u.has_photo? %>
		      					<%= image_tag u.photo_path, {:height => 40, :width=> 40} %>
						<% else %>
							<%= image_tag("/photo_store/no_photo.jpg", :alt => "No image",:height => 50, :width=> 50) %>
						<% end %><br>

                        	        <% else %>
                        	        	    <% count=count-1 %>      
		        	        <% end %>
			 <% end %>
	                 <% if count==0 %>
				<font color="brown" face="times, serif" size="3">Invitation Not Accepted Yet !<br><br></font>
                         <% end %>	
				<font face="times, serif" size="4">Employee Name: <br></font>
				<font color="brown" face="times, serif" size="3"><%= friend.name %><br><br></font>
				<font face="times, serif" size="4">Employee Email: <br></font>
				<font color="brown" face="times, serif" size="3"><%= friend.mail %><br></font>
	       	     	</h5>
                   </div>
			<% if current_user.id == @project.user_id %>
				 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <%= link_to ' Remove from project', friend, :confirm => 'Are you sure you want to delete this user from your project?', :method => :delete %>
			<% end %>
		</div>
		
		<% end %>
	     
	   </div>
	</div>

app/views/projects/_form.html.erb
<html>
<body>

<!--main-container start-->
<div class="main-container">
  <!--start-new-project start-->
  <div class="start-new-project">
  <h2>Start a New Project</h2>
  <div class="start-new-prj-form">
 <div class="left"><img src="/images/start-new-project-tp-bg.png" alt="" /></div>
  <div class="stnp-mid-bg">
  
<%= form_for(@project,:validate => true) do |f| %>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
 <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <tr>
    <td class="pad-rt-6" width="26%" align="right"><%= f.label :project_name %></td>
    <td width="30%">  <%= f.text_field :project_name, :placeholder => "maximum length 18 characters" ,:maxlength => 18, :class =>"input2" %></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
 <tr>
    <td class="pad-rt-6" align="right"> <%= f.label :company_name %></td>
    <td> <%= f.text_field :company_name, :placeholder => "maximum length 23 characters",:maxlength => 23 ,:class=>"input2" %></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
 
    <td colspan="2"><%= f.submit  "Create Project", :class=> "creat-project-button" %></td>
 
    </tr>
</table>

 </div>
  </div>
  </div>
  <!--start-new-project end--> 
</div>

<!--main-container end-->
<% end %>


</body>
</html>

app/views/projects/_invi.html.erb
<html>


<body>

<div id="light" class="white_content"  style="clear:both;display:none" align="left">
<div class="popup-overlay-bg">
 
	 	 

<!--popup-window start-->
<div class="popup-window">
<div class="popup-tp-bg"></div>
<div class="popup-mid-bg">
<div class="popup-wrapper">

<p><font class="font-14">Consultant Invitation:</font> An email will be sent inviting each person to this project. </p>
<div class="popup-form">
 <%= form_for([@project,@project.invites.build]) do |f| %>
<% if @project.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@project.errors.count, "error") %>.
    </div>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :name %><br />
     <%= f.text_field :name ,:class=>"input3" %>
<label> <%= f.label :mail %><br /></label>
<%= f.text_field :mail ,:class=>"input3" %>

<div align="right">
			<a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'"><input name="" type="button" class="cancel-btn" /></a>
		  </div>
<%= f.submit "Send Invitation",:class=>"send-invitation-btn"  %> 

</div>
</div>
</div>
</div>
</div>
<!--popup-window end-->

</div>
<% end %>
	
</body>
</html>


app/views/projects/_micro.html.erb
<html>
<%= form_for([@project,@project.microposts.build],:html => {:multipart => true}) do |f| %>
		<br><br>	
	     <div class="field">
       		<b>Content: </b><br>
		<%= f.text_field :content %>
	       <%= f.file_field :photo  %>
	     </div>
				
  	    <div class="actions" >
    		<%= f.submit %>
  	     </div>
	<% end %>
    

app/views/projects/_project_detail.html.erb
<html>
<br><div align="center">
		<br><br>
	<p><b>
		<font face="times, serif" size="10">Project Detail</font>
		</b></p>
		<hr  width=200 align="left" color="red">
		<p>
  		<font face="times, serif" size="5"><b>Project Name:	</font></b>
  		<font color="brown" face="times, serif" size="4"><%= @project.project_name %> </font>
		</p>

		<p>
		<font face="times, serif" size="5"><b>Company Name:	</font></b>
		<font color="brown" face="times, serif" size="4"><%= @project.company_name %></font>
		</p>
		<% if (@user) %>
		   <% @user.each do |owner| %>
			<% if owner.id == @project.user_id %>
		<p>
		<font face="times, serif" size="5"><b>Owner Name:	</font></b>
		<font color="brown" face="times, serif" size="4"><%= owner.name %></font>
		</p>
			<% end %><% end %>
		<% else %>
		<p>
		<font face="times, serif" size="5"><b>Owner Name:	</font></b>
		<font color="brown" face="times, serif" size="4"><%= @owner %></font>
		</p>
		<% end %>

   </div>

app/views/projects/del.html.erb
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

 <div class="container">
 <div class="center hero-unit">

your project deleted now
<br>
<div align="center">
		<br><br>
		<p><b>
		<font face="times, serif" size="10">Project Detail</font>
		</b></p>
		<hr size=50 width=200 align="left" color="red">
		<p>
  		<font face="times, serif" size="5"><b>Project Name:	</font></b>
  		<font color="brown" face="times, serif" size="4"><%= @project.project_name %></font>
		</p>

		<p>
		<font face="times, serif" size="5"><b>Company Name:	</font></b>
		<font color="brown" face="times, serif" size="4"><%= @project.company_name %></font>
		</p>
   </div>
<%= link_to 'Back', projects_path %>

app/views/projects/edit.html.erb
<html>
</head>
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

 <div class="container">
 <div class="center hero-unit">
<font face="times, serif" size="20"> Editing project</font>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<html>
	<head>
  
	</head>
<body>


<div class="clr"></div>

<!--main-container start-->
<div class="main-container"> 
  <!--dashboard-container start-->
  <div class="dashboard-container">
    <div class="start-project">
      <h2>Start a Project :</h2>
      <p>Have a project or client in mind? Create a project, invite your colleagues or clients, and get started.</p>
      <div class="right"> <%= link_to image_tag("/images/start-new-project-btn.png",:alt=>""), new_project_path %> </div>
    </div>
    <div class="projects"> 

      <!--my project start-->
      <div class="my-projects">
        <h2>My Projects :</h2>
        <div class="project-list">
	<% current_user.projects.each do |project| %>
	<%= link_to project do %> 
          <div class="block-1">
            <div class="client-box">

              <div class="bx-lft">
		<% if current_user.has_photo? %>
      						<%= image_tag current_user.photo_path, {:height => 46, :width=> 46} %>
			  		<% else %>
			      			<%= image_tag("/photo_store/no_photo.jpg", :alt => "No image",:height => 46, :width=> 46) %>
					<% end %>
	      </div>

              <div class="bx-rt">
                <p><strong>Project : <%= project.project_name[0..7] %></strong></p>
              </div>
		<div class="clr"></div>
	    </div>
		<a>Company Name : <h2><%= project.company_name %><h2><br></a>
	  </div>
         <% end %>
	 <% end %>
        </div>
      </div>
      <!--my project end--> 
      
      <!--other project start-->
      <div class="my-projects">
        <h2>Other Projects :</h2>
        <div class="project-list"> 
	  <% @invites.each do |ml| %>
	    <% if (ml.mail == current_user.email) %>
              <% @projects.each do |p| %>
                <% if(ml.project_id==p.id) %>
		  <%= link_to p do %>
	 	  <div class="block-1">
	   	    <div class="client-box">
              		<div class="bx-lft">
			   <% @user.each do |u| %>
			      <% if u.id == p.user_id %>
                                     <% if u.has_photo? %>
      						<%= image_tag u.photo_path, {:height => 46, :width=> 46} %>
			  		<% else %>
			      			<%= image_tag("/photo_store/no_photo.jpg", :alt => "No image",:height => 46, :width=> 46) %>
					<% end %>
			      <% end %>
		           <% end %>
	    		</div>
    	    		<div class="bx-rt">
		          <p><strong>Project : <%= p.project_name[0..7] %></strong></p>
			</div>
			<div class="clr"></div>
		    </div>
			<a>Company Name : <h2><%= p.company_name %></h2></a>
    	  	     
		     <b><%= link_to "Delete Project", ml,:class => "delete-project-btn", :method => :delete,
				 :confirm => 'Are you sure you want to delete this project from your list?' %></b>
		     	
		     
		   </div>
		
		  <% end %>
		 <% end %>
	       <% end %>
	    <% end %>
	  <% end %>
        </div>

      </div>
      <!--other project end--> 

    </div>
  </div>
  <!--dashboard-container end--> 
  
</div>
<!--main-container end--> 

<!-- Preview -->

<!--main-container end--> 

  
<% if current_user.verify==0 %> 
<div id="verify" class="white_content">
 <div class="popup-overlay-bg">
<!--popup-window start-->
   <div class="popup-window">
     <div class="popup-tp-bg"></div>
       <div class="popup-mid-bg">
         <div class="popup-wrapper">
            
 <font color='red'><h2> <blink>You Didn't verify Your Email Yet, Please verify your email... !</blink></h2> </font>

           <div align="right" id="cancel_btn">
  <%= link_to image_tag("/images/cancel-btn.png"), signout_path, :method=> "delete" %>            
           </div>
         </div>
       </div>
     </div>
   </div>
<!--popup-window end-->
 </div>
</div>
<!--preview End-->
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $("#verify").show();
  });
 </script> 

app/views/projects/new.html.erb
<%= render 'form' %>