config/routes.rb
Railscamp::Application.routes.draw do
  

  get "verifys/edit"

  get "verify/edit"

  get "sessions/new"
  resources :verifys
  resources :password_resets

  resources :floads

  resources :comments
  resources :microposts do
resources :comments
resources :floads
end

  resources :users
  resources :invites
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :projects, :only=> [:index, :create, :destroy, :new, :edit, :show, :update, :discuss, :verify]do
	resources :invites
	resources :microposts
        resources :floads 
        

end
match '/notification', :to  => 'users#notification'
get "edit1_user"  => "users#edit1"
get "new_resetpasses"  => "resetpasses#new"
match '/signin',  :to => 'sessions#new'
match '/signout',  :to => 'sessions#destroy'
match '/signup',  :to => 'users#new'
match '/help',    :to   => 'staticpages#help'
  match '/about',   :to => 'staticpages#about'
  match '/contact', :to => 'staticpages#contact'
  match 'projects/show', :to => 'projects#show'
  match 'microposts/show', :to => 'microposts#show'
  get "microposts/show"
  get "projects/show"
  get "staticpages/home"

 get "staticpages/home"
 get "staticpages/about"
 get "staticpages/contact"

   root :to => 'staticpages#index'

match '*a', :to => 'errors#routing'
end

app/models/fload.rb
class Fload < ActiveRecord::Base
  belongs_to :micropost
  belongs_to :project
  belongs_to :user
  attr_accessible :data
validates :user_id, :presence => true
  validates :project_id, :presence => true  



after_save :store_data


def has_data?
File.exists? photo_filename
end

def data=(file_data)
unless file_data.blank?

@file_data = file_data

self.extension = file_data.original_filename.split('.').last.downcase
end
end

# File.join is a cross-platform way of joining directories;
# we could have written "#{RAILS_ROOT}/public/photo_store"
PHOTO_STORE = File.join Rails.root, 'public', 'photo_store'
# where to write the image file to
def photo_filename
File.join PHOTO_STORE, "#{id}.#{extension}"
end
# return a path we can use in HTML for the image
def photo_path
"/photo_store/#{id}.#{extension}"
end



 def store_data
if @file_data
# make the photo_store directory if it doesn't exist already
FileUtils.mkdir_p PHOTO_STORE
# write out the image data to the file
File.open(photo_filename, 'wb') do |f|
f.write(@file_data.read)
end
# ensure file saved only when it newly arrives at model being saved
@file_data = nil
end
end

end

app/controllers/floads_controller.rb
class FloadsController < ApplicationController
  # GET /floads
  # GET /floads.json
  def index
    @floads = Fload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @floads }
    end
  end

  # GET /floads/1
  # GET /floads/1.json
  def show
    @fload = Fload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @fload }
    end
  end

  # GET /floads/new
  # GET /floads/new.json
  def new
    @fload = Fload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @fload }
    end
  end

  # GET /floads/1/edit
  def edit
    @fload = Fload.find(params[:id])
  end

  # POST /floads
  # POST /floads.json
  def create
	 @project = Project.find_by_project_name(params[:project_id])
	@micropost = Micropost.new(params[:micropost])    
	@fload = @micropost.floads.build(params[:fload])
        @fload.project_id = @micropost.project_id
	@fload.micropost = @micropost
    @fload.user = current_user
@project.invites.each do |friend| 
@a=User.find_by_id(current_user.id)
   if @a.email ==  friend.mail 
    @valid_user = friend
   end
end
if  @valid_user || current_user.id == @project.user_id	

    if @fload.save
       redirect_to micropost_path(@project),:flash =>   {:notice => "file uploaded"}
    else
       redirect_to micropost_path(@project)
    end
   else
redirect_to projects_path,:flash =>   {:error => "you are removed from this project."}
end 
  end

  # PUT /floads/1
  # PUT /floads/1.json
  def update
    @fload = Fload.find(params[:id])

    respond_to do |format|
      if @fload.update_attributes(params[:fload])
        format.html { redirect_to @fload, :flash =>   {:notice => "Fload was successfully updated." }}
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @fload.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /floads/1
  # DELETE /floads/1.json
  def destroy
    @fload = Fload.find(params[:id])
    @fload.destroy

    respond_to do |format|
      format.html { redirect_to floads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/floads_helper.rb
module FloadsHelper
end

app/views/floads/_form.html.erb
<%= form_for(@fload) do |f| %>
  <% if @fload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fload.errors.count, "error") %> prohibited this fload from being saved:</h2>

      <ul>
      <% @fload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :micropost %><br />
    <%= f.text_field :micropost %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/floads/edit.html.erb
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

 <div class="container">
 <div class="center hero-unit">

<h1>Editing fload</h1>

<%= render 'form' %>

<%= link_to 'Show', @fload %> |
<%= link_to 'Back', floads_path %>

app/views/floads/index.html.erb
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

 <div class="container">
 <div class="center hero-unit">

<h1>Listing floads</h1>

<table>
  <tr>
    <th>Micropost</th>
    <th>Project</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @floads.each do |fload| %>
  <tr>
    <td><%= fload.micropost %></td>
    <td><%= fload.project %></td>
    <td><%= fload.user %></td>
    <td><%= link_to 'Show', fload %></td>
    <td><%= link_to 'Edit', edit_fload_path(fload) %></td>
    <td><%= link_to 'Destroy', fload, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fload', new_fload_path %>

app/views/floads/new.html.erb
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

 <div class="container">
 <div class="center hero-unit">

<h1>New fload</h1>

<%= render 'form' %>

<%= link_to 'Back', floads_path %>

app/views/floads/show.html.erb
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

 <div class="container">
 <div class="center hero-unit">

<p id="notice"><%= notice %></p>

<p>
  <b>Micropost:</b>
  <%= @fload.micropost %>
</p>

<p>
  <b>Project:</b>
  <%= @fload.project %>
</p>

<p>
  <b>User:</b>
  <%= @fload.user %>
</p>


<%= link_to 'Edit', edit_fload_path(@fload) %> |
<%= link_to 'Back', floads_path %>