config/routes.rb
Railscamp::Application.routes.draw do
  

  get "verifys/edit"

  get "verify/edit"

  get "sessions/new"
  resources :verifys
  resources :password_resets

  resources :floads

  resources :comments
  resources :microposts do
resources :comments
resources :floads
end

  resources :users
  resources :invites
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :projects, :only=> [:index, :create, :destroy, :new, :edit, :show, :update, :discuss, :verify]do
	resources :invites
	resources :microposts
        resources :floads 
        

end
match '/notification', :to  => 'users#notification'
get "edit1_user"  => "users#edit1"
get "new_resetpasses"  => "resetpasses#new"
match '/signin',  :to => 'sessions#new'
match '/signout',  :to => 'sessions#destroy'
match '/signup',  :to => 'users#new'
match '/help',    :to   => 'staticpages#help'
  match '/about',   :to => 'staticpages#about'
  match '/contact', :to => 'staticpages#contact'
  match 'projects/show', :to => 'projects#show'
  match 'microposts/show', :to => 'microposts#show'
  get "microposts/show"
  get "projects/show"
  get "staticpages/home"

 get "staticpages/home"
 get "staticpages/about"
 get "staticpages/contact"

   root :to => 'staticpages#index'

match '*a', :to => 'errors#routing'
end

app/views/layouts/_footer.html.erb
<!--footer-bg start-->
<div class="footer-bg">

<div class="footer">
<div class="left"><p>Copyright © 2011Seasia Consulting. All rights reserved</p></div>

<div class="right">
<a href="#">Terms of Use</a> |
<a href="#">Privacy Policy</a>
</div>
</div>

</div>
<!--footer-bg end-->

app/views/layouts/_header.html.erb
<!--top-bg-box start-->

<% if signed_in? %>
<div class="top-bg-box">
  <div class="top-box">
    <div class="left">
    <%= link_to image_tag("/images/logo.png",:alt=>"NO image") %>
    </div>

     <div class="toplinks">
      <ul>
  
        <li><%= link_to 'Home', {:action => 'index', :controller => 'projects'}   %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li class="divider-none"><%= link_to 'Projects',  {:action => 'index', :controller => 'projects'} %></li>
      </ul>
    </div>
    <div class="right-box"> 
      <!--account-profile start-->
<div class="logout-btn right"><%= link_to image_tag("/images/logout-btn.png"), signout_path, :method=> "delete" %></div>
      <div class="account-profile">
        <div class="col-1">
          <h2><%= current_user.name %></h2>
        </div>
        <div class="col-2"> <% if current_user.has_photo? %>
			       		<%= image_tag(current_user.photo_path, {:height => 50, :width=> 50})%>		
			<% else %>
        			<%= image_tag("/photo_store/no_photo.jpg", :alt => "No image",:height => 50, :width=> 50) %>				
        		<% end %>
        </div>
     
      </div>
      <!--account-profile end--> 
    </div>  
 </div>
</div>
  <% else %>
<div class="top-bg-box">
  <div class="top-box">
<div class="left">
    <%= link_to image_tag("/images/logo.png",:alt=>"NO image") %>
    </div>
    <div class="right-box">
     <div class="home-btn"><%= link_to image_tag("/images/home-button.png",:alt=>""), root_path %></div>
        <div class="login-btn">
          
          <%= link_to image_tag("/images/login-btn.png",:alt=>""), signin_path %>
          
      </div>
    </div>

  <% end %>
  </div>
</div>
<!--top-bg-box end-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag '/stylesheets/main', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Rails Camp</title>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>    
</head>
<body>

 <%= render 'layouts/header' %>
     <div class="container">
      <% flash.each do |key, value| %>
        <div>
<%= content_tag :div, value, :id => "flash_#{key}" %>

      <% end %>
    </div> 
     <%= yield %>

<%= render 'layouts/footer' %>  
  </body>
</html>